config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :reviews
  resources :users, only: [:show] do
    resources :books, except: [:destroy]
  end
  resources :books
  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md fixed-top navbar-light" style="background-color: #e3f2fd;">
    <%= link_to 'Cool Library', '/', class: "navbar-brand"%>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-md-center" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <% if logged_in? %>
                <li class="nav-item ">
                    <%= link_to(user_path(current_user.full_name), class: "nav-link") do %>
                        Profile<span class="sr-only">(current)</span>
                    <% end %>
                </li>

                <li class="nav-item">
                    <%= link_to('All Books', books_path, class: "nav-link") %>
                </li>

                <li class="nav-item">
                    <%= link_to_if(@current_user.author,
                                    "Add New Book",
                                    new_user_book_path(@current_user.full_name),
                                    class: "nav-link") do %>
                    <% end %>
                </li>

                <li class="my-2 my-lg-0">
                    <%= link_to(
                        "Log Out", logout_path,
                        method: :post, 
                        class: 'btn btn-outline-danger btn-sm my-0 mx-md-2'
                    ) %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to('Log In', login_path, class: "nav-link") %>
                </li>
                <li class="nav-item">
                    <%= link_to('Sign Up', signup_path, class: "nav-link") %>
                </li>
            <% end %>
        </ul>
        
    </div>

</nav>