config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :reviews
  resources :users, only: [:show] do
    resources :books, except: [:destroy]
  end
  resources :books
  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/auth/facebook/callback', to: 'sessions#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author, foreign_key: "user_id", class_name: "User"
    has_many :reviews
    has_many :reviewers, through: :reviews, source: :user

    validates :publication_year,
        numericality: { only_integer: true },
        inclusion: { in: 1900..Time.current.year, message: 'should be between 1900 and this year' },
        format: {
        with: /(19|20)\d{2}/i,
        message: "should be a four-digit year"
        }
        validates :title, presence: true
        validates :isbn, presence: true, uniqueness: true


    def average_rating
        Review.where(book_id: id).average(:stars).to_i
    end

    def author_name
        author.full_name
    end

    def popularity_rating
        self.average_rating + self.ratings.count
    end

    def popular?
      if self.average_rating >= 3
        "#{self.full_name}" + " " + "#{self.popularity_rating}"
      end
    end

    def self.popularity

      Book.all.sort_by do |book|
        book.average_rating
      end.reverse
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    # before_action :require_login, only: [:index, :show]
    skip_before_action :require_login, except: [:index, :show]
    before_action :require_author, only: [:new, :create, :edit, :update, :destroy]
    before_action :set_book, only: [:show]
    before_action :set_author_book, only: [:edit, :update]
    
    def index
        if params[:user_id]
          @books = @current_user.books
        else
          @books = Book.all
        end
    end

    def new
        @book = Book.new
    end

    def create
        @book = @current_user.books.build book_params
        if @book.save
            flash["alert alert-info"] = "Book successfully added."
            redirect_to books_path
        else
            render :new
        end
    end

    def show
        if !@book
          flash["alert alert-info"] = "Book does not exist."
        #   render plain: flash[:notice]
          redirect_to books_path
        end
        @review = @book.reviews.build(user_id: @current_user.id)
    end

    def edit
        if !@book
          flash["alert alert-info"] = "This book doesn't yours."
        #   render plain: flash[:notice]
          redirect_to books_path
        end
    end

    def update
        if @book.update(book_params)
            flash["alert alert-info"] = "Book successfully edited."
            redirect_to book_path
        else
            render :edit
        end
    end

    def destroy
        @book.delete
        flash["alert alert-info"] = "Book successfully removed."
        redirect_to books_path
    end

    private

    def set_book
        @book = Book.find_by(id: params[:id])
    end

    def set_author_book
        @book = @current_user.books.find_by(id: params[:id])
    end

    def book_params
        params.require(:book).permit( 
            :title, 
            :isbn, 
            :summary, 
            :publication_year,
            :nbr_page
        )
    end
end

app/views/books/_form.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-danger row justify-content-center" role="alert">
      <div id="error_explanation">
          <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from saving:</h2>
          <ul>
          <% @book.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
          </ul>
      </div>
  </div>
<% end %>

<div class="container">
  <%= form_for @book do |f| %>
    <div class="form-group">
      <%= f.label :title, class: "font-weight-bold" %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :isbn, class: "font-weight-bold" %>
      <%= f.text_field :isbn, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label "Nbr page", class: "font-weight-bold" %>
      <%= f.number_field :nbr_page, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label "Publication Year", class: "font-weight-bold" %>
      <%= f.number_field :publication_year, class: 'form-control' %>
    </div>


    <div class="form-group">
      <%= f.label :summary, class: "font-weight-bold" %>
      <%= f.text_area :summary, class: 'form-control' %>
    </div>

    <div class="form-group">
    <%= link_to "Back", books_path, class: 'btn btn-secondary px-5' %>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<% title 'Edit Book'%>

<h2 class='text-center'>Edit Book</h2>

<%= render partial: 'form', locals: { book: @book} %>

app/views/books/index.html.erb
<% title 'All Books'%>

<div class="container">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-md-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= book.title %></h5>
            <%= link_to "View", user_book_path(book.author_name,book), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
 </div>
</div>

app/views/books/new.html.erb
<% title 'New Book'%>

<h2 class='text-center'>Create a Book</h2>

<%= render partial: 'form', locals: { book: @book} %>


app/views/books/show.html.erb
<% title 'Book' %>

<div class="text-center w-md-50">
<%= link_to "Back to books", books_path %>

<h3><%= @book.title %><br></h3>
<h4>Summary: <%= @book.summary %><br></h4>
<h4>ISBN: <%= @book.isbn %><br></h4>
<h4>Page's number: <%= @book.nbr_page %><br></h4>
<h5>Publish: <%= @book.publication_year %><br></h5>
<h4>Author: <%= @book.author_name %><br></h4>
<p><b>Average Rating:</b> <%= show_stars(@book.average_rating) %>  </p>

  <h5><p>Reviews:</h5>
  <div class="row justify-content-center">
  <ul class="list-group col-sm-8"> 
  <% @book.reviews.each do |review| %></p>
    <% if review.id%>
    
      <%= link_to(review_path(review), class: " list-group-item list-group-item-action ") do %>
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1"><%= review.user.full_name%></h5>
          <small><%= show_stars(review.stars)%></small>
        </div>
     <p class="mb-1"><%= review.comments%></p>
    <%# <small>Donec id elit non mi porta.</small> %>
      <% end %>
    
    <%end%>
  <% end %>
  </ul>
  </div>
<p class="mb-1"><b>Add review:</b></p>
<%= form_for @review, html: {class: 'pt-2 form-horizontal'} do |f| %>

  <div class="form-group row justify-content-center">
    <%= f.label :stars, class: "col-md-2 control-label" %>
    <div class="col-md-7">
      <%= f.select :stars, [[1], [2], [3], [4], [5]],{}, {class: "form-control "} %>
    </div>
  </div>

    <%= f.hidden_field :book_id%>
    <%= f.hidden_field :user_id%>

  <div class="form-group row justify-content-center">
    <%= f.label :comments, class: "col-md-2 control-label" %>
    <div class="col-md-7">
      <%= f.text_area :comments %>
      </div>
  </div>
  <div class="form-group row justify-content-center">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>
<%# link_to "Back", books_path, class: 'btn btn-secondary' %>

<% if @current_user == @book.author %> 
  <%= link_to "Edit", edit_user_book_path(@book.author_name, @book), class: 'btn btn-info col-sm-4' %> 
  <%= form_tag book_path(@book), method: "delete", data: { confirm: "Are you sure you want to delete this item?" } do %>
    <%= submit_tag "Delete", class: 'btn btn-danger col-sm-4' %>
  <% end %> 
<% end %>
<div>